### PR TITLE
fix(webapp): fix event teaser date from start to end by new components

### LINKED ISSUE #6379: 🐛 [Bug] Webapp – Event Teaser – Date from Start to End
## 🐛 Bugreport

Webapp – Event Teaser – Date from Start to End.

Have a look into the PR #6358 or if it's merged into the master at event view page and overtake it from there.

Bildschirmfoto 2023-06-06 um 11 44 03

### PR DESCRIPTION
**Pull request by Tirokk**
## 🍰 Pullrequest

Fix event teaser date from start to end by new components.

### Issues

- fixes #6379 

### Todo

- [x] create component for date range
- [x] create component for location

### CODE REVIEW

File: webapp/components/DateTimeRange/DateTimeRange.vue [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+    },
+  },
+  computed: {
+    startDateAsDate() {
+      return new Date(this.startDate)
+    },
+    endDateAsDate() {
+      return this.endDate ? new Date(this.endDate) : null
+    },
+    isSameDay() {
```
Comment (Mogge) [inline webapp/components/DateTimeRange/DateTimeRange.vue:64]: Do you use the same name as the imported  `isSameDate` method on purpose? This might be confusing. Sure that there are no problems?

File: webapp/components/DateTimeRange/DateTimeRange.vue [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+      return !this.endDateAsDate || isSameDay(this.endDateAsDate, this.startDateAsDate)
+    },
+    isSameYear() {
+      return !this.endDateAsDate || isSameYear(this.endDateAsDate, this.startDateAsDate)
+    },
+    getStartDateString() {
+      let startDateFormat = 'dd.MM.yyyy'
```
Comment (Mogge) [inline webapp/components/DateTimeRange/DateTimeRange.vue:71]: This is German. This must be localized.

**Review by Mogge — CHANGES_REQUESTED** [review]

**Comment by Tirokk** [comment]
I find this ugly and have to talk about. @Elweyn @maeckes-infinitylabs @ogerly 

Bildschirmfoto 2023-06-07 um 20 04 44

**Comment by Elweyn** [comment]
image

**Review by Elweyn — APPROVED** [review]
Please make follow issue for Unit Test of the components

**Comment by Tirokk** [comment]
> Please make follow issue for Unit Test of the components

Done here #6407

**Review by Mogge — APPROVED** [review]
