### PR TITLE
fix: My Groups Count Includes Pending Membership

### LINKED ISSUE #5628: 🐛 [Bug] Counter of my groups is incorrect due to pending memberships
## 🐛 Bugreport

Counter of my groups is incorrect due to pending memberships

### PR DESCRIPTION
**Pull request by Mogge**
### Issues
- fixes #5628 

### Todo

- [X] None

### CODE REVIEW

File: backend/src/schema/resolvers/groups.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ export default {
         if (isMember) {
           cypher = `MATCH (user:User)-[membership:MEMBER_OF]->(group:Group)
                     WHERE user.id = $userId
-                    AND membership.role IN ['usual', 'admin', 'owner']
+                    AND membership.role IN ['usual', 'admin', 'owner', 'pending']
```
Comment (ulfgebhardt) [inline backend/src/schema/resolvers/groups.js:100]: is there no way to reduce the two queries to one, so this problem will never araise in the future anymore?

**Review by ulfgebhardt — APPROVED** [review]
