### PR TITLE
fix(webapp): change theme color to be brandable

### LINKED ISSUE #8003: 🐛 [Bug] Webapp – Theme Color is not Brandable
## 🐛 Bugreport

Theme Color is not Brandable

### Todo

- adjust `theme_color: '#17b53f'` in `webapp/constants/manifest.js`

### PR DESCRIPTION
**Pull request by Tirokk**
## 🍰 Pullrequest

Change theme color to be brandable.

### Issues

- fixes #8003 

### Todo

- [x] adjust `theme_color: '#17b53f'` in `webapp/constants/manifest.js`

### CODE REVIEW

File: webapp/constants/manifest.js [hunk 1]
```diff
@@ -1,9 +1,10 @@
 import metadata from './metadata.js'
-const { APPLICATION_NAME, APPLICATION_SHORT_NAME, APPLICATION_DESCRIPTION } = metadata
+const { APPLICATION_NAME, APPLICATION_SHORT_NAME, APPLICATION_DESCRIPTION, THEME_COLOR } = metadata
+
 export default {
   name: APPLICATION_NAME,
   short_name: APPLICATION_SHORT_NAME,
   description: APPLICATION_DESCRIPTION,
-  theme_color: '#17b53f',
+  theme_color: THEME_COLOR,
```
Comment (Tirokk) [inline webapp/constants/manifest.js:8]: - using a new SCSS name like `'$theme-color'` doesn't work here unfortunately
- to import the color from SCSS gives a nuxt error unfortunately

**Comment by Tirokk** [comment]
If there is a better solution for this, please let me know.
@mahula @roschaefer @ulfgebhardt

**Review by roschaefer — APPROVED** [review]
I think it's fine
